// Generated item data structs
// Database contains 65 total items

// power      8 bitsr
// item_level 4 bits
// item_type  4 bits
// flags
//    x5 padding bits
//    consumable
//    consumable_party
//    consumable_spellbook

// Individual items data
// 0 - name - .power = ABILITY_COUNT, .item_level = 1, .item_type = MAGICAL,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = ABILITY_COUNT, .data = 0x41, .flags = 0b00000011 },
// 1 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000001 },
// 2 - name - .power = 100, .item_level = 1, .item_type = MAGICAL,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x41, .flags = 0b00000000 },
// 3 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000011 },
// 4 - name - .power = 6, .item_level = 1, .item_type = BAG,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 6, .data = 0x51, .flags = 0b00000000 },
// 5 - name - .power = 2, .item_level = 1, .item_type = BAG,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 2, .data = 0x51, .flags = 0b00000000 },
// 6 - name - .power = 4, .item_level = 1, .item_type = BAG,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 4, .data = 0x51, .flags = 0b00000000 },
// 7 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 8 - name - .power = 100, .item_level = 1, .item_type = MAGICAL,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x41, .flags = 0b00000000 },
// 9 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 10 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 11 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 12 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 13 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 14 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 15 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000001 },
// 16 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 17 - name - .power = 100, .item_level = 1, .item_type = MAGICAL,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x41, .flags = 0b00000001 },
// 18 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000001 },
// 19 - name - .power = 100, .item_level = 1, .item_type = FOOD,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x11, .flags = 0b00000011 },
// 20 - name - .power = 100, .item_level = 1, .item_type = FOOD,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x11, .flags = 0b00000011 },
// 21 - name - .power = 100, .item_level = 1, .item_type = FOOD,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x11, .flags = 0b00000011 },
// 22 - name - .power = 100, .item_level = 1, .item_type = FOOD,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x11, .flags = 0b00000011 },
// 23 - name - .power = 100, .item_level = 1, .item_type = FOOD,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x11, .flags = 0b00000011 },
// 24 - name - .power = 100, .item_level = 1, .item_type = FOOD,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x11, .flags = 0b00000011 },
// 25 - name - .power = 100, .item_level = 1, .item_type = FOOD,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x11, .flags = 0b00000011 },
// 26 - name - .power = 100, .item_level = 1, .item_type = FOOD,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x11, .flags = 0b00000011 },
// 27 - name - .power = 100, .item_level = 1, .item_type = FOOD,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x11, .flags = 0b00000011 },
// 28 - name - .power = 100, .item_level = 1, .item_type = FOOD,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x11, .flags = 0b00000011 },
// 29 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000011 },
// 30 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 31 - name - .power = 100, .item_level = 1, .item_type = MAGICAL,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x41, .flags = 0b00000000 },
// 32 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000011 },
// 33 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 34 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 35 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 36 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 37 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000011 },
// 38 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000001 },
// 39 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000011 },
// 40 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000011 },
// 41 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000011 },
// 42 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000011 },
// 43 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000001 },
// 44 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000011 },
// 45 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000001 },
// 46 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000011 },
// 47 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000001 },
// 48 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 1 } 
{ .power = 100, .data = 0x01, .flags = 0b00000101 },
// 49 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000011 },
// 50 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000001 },
// 51 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000001 },
// 52 - name - .power = 100, .item_level = 1, .item_type = MAGICAL,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x41, .flags = 0b00000011 },
// 53 - name - .power = 100, .item_level = 1, .item_type = MAGICAL,  flags = { .consumable = 1, .consumable_party = 1, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x41, .flags = 0b00000011 },
// 54 - name - .power = 1, .item_level = 1, .item_type = MAGICAL,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 1, .data = 0x41, .flags = 0b00000001 },
// 55 - name - .power = SPELL_COUNT, .item_level = 1, .item_type = MAGICAL,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = SPELL_COUNT, .data = 0x41, .flags = 0b00000001 },
// 56 - name - .power = 100, .item_level = 1, .item_type = MAGICAL,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x41, .flags = 0b00000000 },
// 57 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000001 },
// 58 - name - .power = SPELL_COUNT, .item_level = 1, .item_type = MAGICAL,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = SPELL_COUNT, .data = 0x41, .flags = 0b00000001 },
// 59 - name - .power = 1, .item_level = 1, .item_type = MAGICAL,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 1, .data = 0x41, .flags = 0b00000001 },
// 60 - name - .power = 100, .item_level = 1, .item_type = POTION,  flags = { .consumable = 1, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x01, .flags = 0b00000001 },
// 61 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 62 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 63 - name - .power = 100, .item_level = 1, .item_type = COMMON,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x31, .flags = 0b00000000 },
// 64 - name - .power = 100, .item_level = 1, .item_type = MAGICAL,  flags = { .consumable = 0, .consumable_party = 0, .consumable_spellbook = 0 } 
{ .power = 100, .data = 0x41, .flags = 0b00000000 },

//COUNT = 65;
