// Generated object data structs
// Database contains 35 total objects

//       8 bits - .power = { 8 bits } 
//    2x 4 bits - .data  = { .object_type = { 4 bits }, .level = { 4 bits } }
//       8 bits - .flags = { pad1, pad0, .water, .nook,  .hallway, .on_step, .interactable, .consumable  }

// total 3 bytes
// Individual objects data - count = 35
//    0 - ALTAR
{ .power = 0x64, .data = 0x01, .flags = 0b00000010 },
//    1 - CABINET_BOOK
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    2 - CABINET_JEWELLERY
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    3 - CABINET_SCROLL
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    4 - CAULDRON
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    5 - COFFIN_COFFIN
{ .power = 0x64, .data = 0x01, .flags = 0b00010011 },
//    6 - COFFIN_SARCOPHAGUS
{ .power = 0x64, .data = 0x01, .flags = 0b00010011 },
//    7 - CORPSE_HANGING
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    8 - CORPSE_LAID
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    9 - DOOR_BARRED
{ .power = 0x04, .data = 0x01, .flags = 0b00001110 },
//    10 - DOOR_IRON
{ .power = 0x03, .data = 0x01, .flags = 0b00001110 },
//    11 - DOOR_STONE
{ .power = 0x05, .data = 0x01, .flags = 0b00001110 },
//    12 - DOOR_WICKER
{ .power = 0x01, .data = 0x01, .flags = 0b00001110 },
//    13 - DOOR_WOOD
{ .power = 0x02, .data = 0x01, .flags = 0b00001110 },
//    14 - EGRESS_CAVE
{ .power = 0x05, .data = 0x01, .flags = 0b00010010 },
//    15 - EGRESS_LADDER
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    16 - EGRESS_STAIRS
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    17 - FIRE_BONFIRE
{ .power = 0x64, .data = 0x01, .flags = 0b00000010 },
//    18 - FIRE_BRAZIER
{ .power = 0x64, .data = 0x01, .flags = 0b00000010 },
//    19 - FIRE_CAMPFIRE
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    20 - FIRE_STANDING_TORCH
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    21 - FIRE_WALL_TORCH
{ .power = 0x64, .data = 0x01, .flags = 0b00000010 },
//    22 - FOUNTAIN_ACID
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    23 - FOUNTAIN_BLOOD
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    24 - FOUNTAIN_WATER
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    25 - TREASURE_BARREL
{ .power = 0x64, .data = 0x01, .flags = 0b00000011 },
//    26 - TREASURE_BASKET
{ .power = 0x64, .data = 0x01, .flags = 0b00000011 },
//    27 - TREASURE_CHEST
{ .power = 0x64, .data = 0x01, .flags = 0b00000011 },
//    28 - TREASURE_COFFER
{ .power = 0x05, .data = 0x01, .flags = 0b00010011 },
//    29 - TREASURE_CRATE
{ .power = 0x05, .data = 0x01, .flags = 0b00010011 },
//    30 - TREASURE_TRUNK
{ .power = 0x05, .data = 0x01, .flags = 0b00010011 },
//    31 - TREASURE_URN
{ .power = 0x64, .data = 0x01, .flags = 0b00000011 },
//    32 - TREASURE_VAULT
{ .power = 0x05, .data = 0x01, .flags = 0b00010011 },
//    33 - WARD
{ .power = 0x05, .data = 0x01, .flags = 0b00001100 },
//    34 - WELL
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },

//COUNT = 35;
