// Generated creature types
// Database contains 253 total entities

// Individual types strings
{ .typeA = 3, .typeB = 11}, //Aboleth
{ .typeA = 7, .typeB = 14}, //Adze
{ .typeA = 11, .typeB = 4}, //Aeon
{ .typeA = 3, .typeB = 7}, //Akkorokamui
{ .typeA = 13, .typeB = 4}, //Alp
{ .typeA = 0, .typeB = 8}, //Alraune
{ .typeA = 8, .typeB = 15}, //Alux
{ .typeA = 7, .typeB = 11}, //Ammit
{ .typeA = 5, .typeB = 7}, //Amphiptere
{ .typeA = 7, .typeB = 14}, //Amphisbaena
{ .typeA = 7, .typeB = 8}, //Anansi
{ .typeA = 4, .typeB = 11}, //Angel
{ .typeA = 7, .typeB = 15}, //Ankheg
{ .typeA = 7, .typeB = 15}, //Ankylosaurus
{ .typeA = 5, .typeB = 7}, //Anzu
{ .typeA = 4, .typeB = 11}, //Archon
{ .typeA = 8, .typeB = 9}, //Baba Yaga
{ .typeA = 6, .typeB = 13}, //Balor
{ .typeA = 12, .typeB = 2}, //Banshee
{ .typeA = 7, .typeB = 12}, //Barghest
{ .typeA = 7, .typeB = 5}, //Basilisk
{ .typeA = 4, .typeB = 11}, //Beholder
{ .typeA = 8, .typeB = 15}, //Boggart
{ .typeA = 8, .typeB = 13}, //Bogie
{ .typeA = 7, .typeB = 14}, //Bonnacon
{ .typeA = 8, .typeB = 7}, //Brag
{ .typeA = 8, .typeB = 15}, //Brownie
{ .typeA = 10, .typeB = 7}, //Bugbear
{ .typeA = 6, .typeB = 13}, //Buggane
{ .typeA = 7, .typeB = 15}, //Bulette
{ .typeA = 4, .typeB = 11}, //Byakhee
{ .typeA = 8, .typeB = 2}, //Cailleach
{ .typeA = 7, .typeB = 8}, //Caladrius
{ .typeA = 13, .typeB = 7}, //Callicantzaros
{ .typeA = 13, .typeB = 10}, //Cambion
{ .typeA = 7, .typeB = 14}, //Catoblepas
{ .typeA = 8, .typeB = 7}, //Cat Sidhe
{ .typeA = 7, .typeB = 10}, //Centaur
{ .typeA = 7, .typeB = 13}, //Cerberus
{ .typeA = 8, .typeB = 10}, //Changeling
{ .typeA = 7, .typeB = 5}, //Chimera
{ .typeA = 12, .typeB = 7}, //Chonchón
{ .typeA = 7, .typeB = 14}, //Chupacabra
{ .typeA = 8, .typeB = 15}, //Cluricaun
{ .typeA = 7, .typeB = 5}, //Cockatrice
{ .typeA = 8, .typeB = 7}, //Cù Sidhe
{ .typeA = 8, .typeB = 11}, //Cŵn Annwn
{ .typeA = 6, .typeB = 10}, //Cyclops
{ .typeA = 13, .typeB = 11}, //Demon
{ .typeA = 11, .typeB = 4}, //Deva
{ .typeA = 7, .typeB = 3}, //Dingonek
{ .typeA = 8, .typeB = 15}, //Dobbie
{ .typeA = 7, .typeB = 3}, //Dobhran
{ .typeA = 12, .typeB = 13}, //Dolor
{ .typeA = 8, .typeB = 15}, //Domovoi
{ .typeA = 4, .typeB = 10}, //Doppelganger
{ .typeA = 5, .typeB = 12}, //Dracolich
{ .typeA = 5, .typeB = 1}, //Dragon
{ .typeA = 5, .typeB = 7}, //Drake
{ .typeA = 6, .typeB = 12}, //Draugr
{ .typeA = 0, .typeB = 8}, //Dryad
{ .typeA = 10, .typeB = 15}, //Duergar
{ .typeA = 12, .typeB = 11}, //Dullahan
{ .typeA = 8, .typeB = 7}, //Dunnie
{ .typeA = 10, .typeB = 15}, //Dwarf
{ .typeA = 4, .typeB = 12}, //Ebon
{ .typeA = 13, .typeB = 1}, //Efreet
{ .typeA = 4, .typeB = 2}, //Elemental Air
{ .typeA = 4, .typeB = 15}, //Elemental Earth
{ .typeA = 4, .typeB = 1}, //Elemental Fire
{ .typeA = 4, .typeB = 3}, //Elemental Water
{ .typeA = 10, .typeB = 13}, //Dark Elf
{ .typeA = 10, .typeB = 0}, //High Elf
{ .typeA = 10, .typeB = 9}, //Wood Elf
{ .typeA = 7, .typeB = 8}, //Enfield
{ .typeA = 13, .typeB = 11}, //Erinyes
{ .typeA = 8, .typeB = 15}, //Erlking
{ .typeA = 6, .typeB = 7}, //Fachan
{ .typeA = 0, .typeB = 8}, //Fairy
{ .typeA = 8, .typeB = 10}, //Far Darrig
{ .typeA = 8, .typeB = 15}, //Fenoderee
{ .typeA = 7, .typeB = 11}, //Fenrir
{ .typeA = 12, .typeB = 8}, //Fetch
{ .typeA = 8, .typeB = 10}, //Fir Darrig
{ .typeA = 8, .typeB = 1}, //Follet
{ .typeA = 6, .typeB = 13}, //Fomorian
{ .typeA = 8, .typeB = 3}, //Fossegrim
{ .typeA = 8, .typeB = 3}, //Gallybeg
{ .typeA = 7, .typeB = 3}, //Gallytrot
{ .typeA = 8, .typeB = 10}, //Gancanogh
{ .typeA = 15, .typeB = 13}, //Gargoyle
{ .typeA = 12, .typeB = 4}, //Ghost
{ .typeA = 12, .typeB = 14}, //Ghoul
{ .typeA = 6, .typeB = 2}, //Frost Giant
{ .typeA = 6, .typeB = 15}, //Stone Giant
{ .typeA = 0, .typeB = 8}, //Gilly Dhu
{ .typeA = 8, .typeB = 3}, //Glashtig
{ .typeA = 10, .typeB = 15}, //Gnome
{ .typeA = 8, .typeB = 1}, //Goannotgh
{ .typeA = 10, .typeB = 8}, //Goblin
{ .typeA = 15, .typeB = 11}, //Golem
{ .typeA = 12, .typeB = 11}, //Grim Reaper
{ .typeA = 8, .typeB = 3}, //Grindylow
{ .typeA = 8, .typeB = 3}, //Groac'h
{ .typeA = 5, .typeB = 7}, //Grootslang
{ .typeA = 8, .typeB = 7}, //Gruagach
{ .typeA = 8, .typeB = 7}, //Gruaghair
{ .typeA = 8, .typeB = 7}, //Gruff
{ .typeA = 12, .typeB = 8}, //Gwillion
{ .typeA = 7, .typeB = 12}, //Gwyllgi
{ .typeA = 13, .typeB = 10}, //Hag
{ .typeA = 7, .typeB = 13}, //Harpy
{ .typeA = 7, .typeB = 5}, //Hippogriff
{ .typeA = 8, .typeB = 15}, //Hob
{ .typeA = 10, .typeB = 8}, //Hobgoblin
{ .typeA = 7, .typeB = 11}, //Hou
{ .typeA = 8, .typeB = 10}, //Huldra
{ .typeA = 10, .typeB = 9}, //Human
{ .typeA = 4, .typeB = 10}, //Illithid
{ .typeA = 13, .typeB = 8}, //Imp
{ .typeA = 7, .typeB = 13}, //Impundulu
{ .typeA = 11, .typeB = 14}, //Jackal
{ .typeA = 7, .typeB = 8}, //Jackalope
{ .typeA = 13, .typeB = 1}, //Jinn
{ .typeA = 5, .typeB = 3}, //Jörmungandr
{ .typeA = 6, .typeB = 2}, //Jötunn
{ .typeA = 12, .typeB = 8}, //Jumbie
{ .typeA = 3, .typeB = 10}, //Kappa
{ .typeA = 7, .typeB = 3}, //Kelpie
{ .typeA = 5, .typeB = 11}, //Kirin
{ .typeA = 7, .typeB = 8}, //Kitsune
{ .typeA = 10, .typeB = 15}, //Kobold
{ .typeA = 8, .typeB = 15}, //Korred
{ .typeA = 8, .typeB = 3}, //Korrigan
{ .typeA = 12, .typeB = 11}, //Koschei
{ .typeA = 11, .typeB = 3}, //Kraken
{ .typeA = 11, .typeB = 7}, //Lamassu
{ .typeA = 13, .typeB = 10}, //Lamia
{ .typeA = 8, .typeB = 12}, //Leanan Sídhe
{ .typeA = 12, .typeB = 13}, //Lemure
{ .typeA = 8, .typeB = 15}, //Leprechaun
{ .typeA = 8, .typeB = 0}, //Leshy
{ .typeA = 3, .typeB = 11}, //Leviathan
{ .typeA = 12, .typeB = 2}, //Lich
{ .typeA = 9, .typeB = 12}, //Lilitu
{ .typeA = 5, .typeB = 7}, //Lindworm
{ .typeA = 7, .typeB = 10}, //Lizardfolk
{ .typeA = 7, .typeB = 13}, //Loup-Garou
{ .typeA = 8, .typeB = 10}, //Lutin
{ .typeA = 12, .typeB = 8}, //Ly Erg
{ .typeA = 7, .typeB = 14}, //Manticore
{ .typeA = 7, .typeB = 0}, //Mapinguari
{ .typeA = 7, .typeB = 13}, //Mara
{ .typeA = 9, .typeB = 3}, //Marid
{ .typeA = 12, .typeB = 3}, //Marool
{ .typeA = 7, .typeB = 4}, //Medusa
{ .typeA = 8, .typeB = 3}, //Menehune
{ .typeA = 10, .typeB = 3}, //Mermaid
{ .typeA = 8, .typeB = 3}, //Merrow
{ .typeA = 11, .typeB = 4}, //Mi-Go
{ .typeA = 4, .typeB = 15}, //Mimic
{ .typeA = 7, .typeB = 6}, //Minotaur
{ .typeA = 10, .typeB = 15}, //Mole People
{ .typeA = 8, .typeB = 3}, //Morgen
{ .typeA = 12, .typeB = 13}, //Moroi
{ .typeA = 12, .typeB = 11}, //Mummy
{ .typeA = 8, .typeB = 15}, //Muryan
{ .typeA = 10, .typeB = 15}, //Myrmidon
{ .typeA = 8, .typeB = 3}, //Näcken
{ .typeA = 7, .typeB = 10}, //Nāga
{ .typeA = 8, .typeB = 3}, //Naiad
{ .typeA = 8, .typeB = 3}, //Nereid
{ .typeA = 4, .typeB = 13}, //Nightgaunt
{ .typeA = 8, .typeB = 3}, //Nix
{ .typeA = 12, .typeB = 3}, //Nuckelavee
{ .typeA = 8, .typeB = 0}, //Nymph
{ .typeA = 4, .typeB = 14}, //Ochre Jelly
{ .typeA = 6, .typeB = 7}, //Ogre
{ .typeA = 6, .typeB = 13}, //Oni
{ .typeA = 4, .typeB = 14}, //Ooze
{ .typeA = 10, .typeB = 11}, //Oracle
{ .typeA = 10, .typeB = 7}, //Orc
{ .typeA = 8, .typeB = 15}, //Oread
{ .typeA = 7, .typeB = 4}, //Owlbear
{ .typeA = 7, .typeB = 11}, //Pegasus
{ .typeA = 7, .typeB = 13}, //Peryton
{ .typeA = 12, .typeB = 4}, //Phantom
{ .typeA = 5, .typeB = 3}, //Phaya Nak
{ .typeA = 1, .typeB = 7}, //Phoenix
{ .typeA = 13, .typeB = 1}, //Pit Fiend
{ .typeA = 8, .typeB = 1}, //Pixie
{ .typeA = 12, .typeB = 4}, //Poltergeist
{ .typeA = 5, .typeB = 14}, //Pseudodragon
{ .typeA = 0, .typeB = 14}, //Qat
{ .typeA = 4, .typeB = 5}, //Quetzalcoatl
{ .typeA = 7, .typeB = 11}, //Quinotaur
{ .typeA = 13, .typeB = 7}, //Rakshasa
{ .typeA = 8, .typeB = 13}, //Redcap
{ .typeA = 7, .typeB = 2}, //Remorhaz
{ .typeA = 12, .typeB = 13}, //Revenant
{ .typeA = 3, .typeB = 5}, //River Serpent
{ .typeA = 7, .typeB = 11}, //Roc
{ .typeA = 12, .typeB = 3}, //Rusalka
{ .typeA = 7, .typeB = 8}, //Satyr
{ .typeA = 7, .typeB = 3}, //Scylla
{ .typeA = 3, .typeB = 5}, //Sea Serpent
{ .typeA = 8, .typeB = 3}, //Selkie
{ .typeA = 12, .typeB = 4}, //Shade
{ .typeA = 12, .typeB = 4}, //Shadow
{ .typeA = 8, .typeB = 3}, //Siren
{ .typeA = 12, .typeB = 10}, //Skeleton
{ .typeA = 12, .typeB = 4}, //Specter
{ .typeA = 11, .typeB = 7}, //Sphynx
{ .typeA = 14, .typeB = 6}, //Giant Spider
{ .typeA = 12, .typeB = 13}, //Striga
{ .typeA = 13, .typeB = 8}, //Succubus
{ .typeA = 5, .typeB = 14}, //Tarasque
{ .typeA = 7, .typeB = 4}, //Thunderbird
{ .typeA = 6, .typeB = 11}, //Titan
{ .typeA = 12, .typeB = 11}, //Tomb Wraith
{ .typeA = 0, .typeB = 6}, //Treant
{ .typeA = 6, .typeB = 4}, //Troll
{ .typeA = 4, .typeB = 10}, //Umber Hulk
{ .typeA = 8, .typeB = 3}, //Undine
{ .typeA = 7, .typeB = 11}, //Unicorn
{ .typeA = 13, .typeB = 7}, //Uriaș
{ .typeA = 13, .typeB = 10}, //Uruk
{ .typeA = 9, .typeB = 11}, //Valkyrie
{ .typeA = 12, .typeB = 13}, //Vampire
{ .typeA = 12, .typeB = 13}, //Vetala
{ .typeA = 8, .typeB = 3}, //Vodyanoi
{ .typeA = 4, .typeB = 12}, //Void Wraith
{ .typeA = 7, .typeB = 13}, //Warg
{ .typeA = 12, .typeB = 2}, //Wendigo
{ .typeA = 7, .typeB = 10}, //Werewolf
{ .typeA = 12, .typeB = 10}, //Wight
{ .typeA = 8, .typeB = 1}, //Will-o'-Wisp
{ .typeA = 10, .typeB = 8}, //Witch
{ .typeA = 8, .typeB = 0}, //Wood Wose
{ .typeA = 12, .typeB = 4}, //Wraith
{ .typeA = 5, .typeB = 2}, //Wyrm
{ .typeA = 5, .typeB = 14}, //Wyvern
{ .typeA = 8, .typeB = 3}, //Xana
{ .typeA = 7, .typeB = 11}, //Xanthus
{ .typeA = 4, .typeB = 15}, //Xorn
{ .typeA = 7, .typeB = 11}, //Yale
{ .typeA = 7, .typeB = 12}, //Yeth
{ .typeA = 2, .typeB = 7}, //Yeti
{ .typeA = 3, .typeB = 11}, //Zaratan
{ .typeA = 8, .typeB = 1}, //Ziburinis
{ .typeA = 7, .typeB = 11}, //Ziz
{ .typeA = 5, .typeB = 1}, //Zmey
{ .typeA = 12, .typeB = 10}, //Zombie

//ALL_TYPES_COUNT = 253;
