// Generated object data structs
// Database contains 107 total objects

//       8 bits - .power = { 8 bits } 
//    2x 4 bits - .data  = { .object_type = { 4 bits }, .level = { 4 bits } }
//       8 bits - .flags = { pad1, pad0, .water, .nook,  .hallway, .on_step, .interactable, .consumable  }

// total 3 bytes
// Individual objects data - count = 107
//    0 - ALTAR
{ .power = 0x64, .data = 0x01, .flags = 0b00000010 },
//    1 - ANVIL
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    2 - BANNER_ELF
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    3 - BANNER_GOBLIN
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    4 - BANNER_ORC
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    5 - BAPTISMAL_FONT
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    6 - BED_COT
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    7 - BED_SINGLE
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    8 - BED_TENT
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    9 - BELL
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    10 - BOMB_TNT
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    11 - CABINET_BOOK
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    12 - CABINET_JEWELLERY
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    13 - CABINET_SCROLL
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    14 - CAULDRON
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    15 - COFFIN_COFFIN
{ .power = 0x64, .data = 0x01, .flags = 0b00010011 },
//    16 - COFFIN_SARCOPHAGUS
{ .power = 0x64, .data = 0x01, .flags = 0b00010011 },
//    17 - CONFESSIONAL_TREE
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    18 - CORPSE_CRUCIFIED
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    19 - CORPSE_HANGING
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    20 - CORPSE_IMPALED
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    21 - CORPSE_LAID
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    22 - DOOR_BARRED
{ .power = 0x04, .data = 0x01, .flags = 0b00001110 },
//    23 - DOOR_IRON
{ .power = 0x03, .data = 0x01, .flags = 0b00001110 },
//    24 - DOOR_JAILBAR
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    25 - DOOR_STONE
{ .power = 0x05, .data = 0x01, .flags = 0b00001110 },
//    26 - DOOR_WICKER
{ .power = 0x01, .data = 0x01, .flags = 0b00001110 },
//    27 - DOOR_WOOD
{ .power = 0x02, .data = 0x01, .flags = 0b00001110 },
//    28 - EGRESS_CAVE
{ .power = 0x05, .data = 0x01, .flags = 0b00010010 },
//    29 - EGRESS_LADDER
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    30 - EGRESS_ROPE
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    31 - EGRESS_STAIRS
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    32 - FIRE_BONFIRE
{ .power = 0x64, .data = 0x01, .flags = 0b00000010 },
//    33 - FIRE_BRAZIER
{ .power = 0x64, .data = 0x01, .flags = 0b00000010 },
//    34 - FIRE_CAMPFIRE
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    35 - FIRE_PYRE
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    36 - FIRE_STANDING_TORCH
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    37 - FIRE_WALL_TORCH
{ .power = 0x64, .data = 0x01, .flags = 0b00000010 },
//    38 - FORGE
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    39 - FOUNTAIN_ACID
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    40 - FOUNTAIN_BLOOD
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    41 - FOUNTAIN_OOZE
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    42 - FOUNTAIN_WATER
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    43 - GEODE_CRYSTAL
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    44 - HEADING_BLOCK
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    45 - HIGH_CROSS
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    46 - ICE_BOX
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    47 - IDOL_OF_HERNE
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    48 - INSCRIPTION
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    49 - LOOM
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    50 - METEORITE
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    51 - MIRROR_REVERSAL
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    52 - MIRROR_STANDING
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    53 - OBELISK
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    54 - PAD_DISPLACEMENT
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    55 - PAD_TELEPORT
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    56 - PALANTIR
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    57 - POOL_REFLECTION
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    58 - PORTAL_ALFHEIM
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    59 - PORTAL_ATLANTIS
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    60 - PORTAL_ELYSIUM
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    61 - PORTAL_HEL
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    62 - PORTAL_JOTUNHEIM
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    63 - PORTAL_MAGE
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    64 - PORTAL_OLYMPUS
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    65 - PORTAL_TAKAMA
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    66 - PORTAL_TARTARUS
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    67 - PORTAL_VALHALLA
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    68 - POT_OF_GOLD
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    69 - RACK_ARMOR
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    70 - RACK_WEAPON
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    71 - SHIPWRECK
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    72 - SHRINE_MINERVA
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    73 - SHRINE_POSEIDON
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    74 - SHRINE_SAINT_MARY
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    75 - SIGIL_PENTAGRAM
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    76 - STATUE_EXPLORER
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    77 - STATUE_HERO
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    78 - STATUE_KING
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    79 - STATUE_WEEPING
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    80 - STILL
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    81 - SUNDIAL
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    82 - TORTURE_CUCKING_STOOL
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    83 - TORTURE_RACK
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    84 - TORTURE_SCOLDS_BRIDLE
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    85 - TORTURE_STOCKS
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    86 - TORTURE_STRAPPADO
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    87 - TORTURE_WHIPPING_POST
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    88 - TREASURE_BARREL
{ .power = 0x64, .data = 0x01, .flags = 0b00000011 },
//    89 - TREASURE_BASKET
{ .power = 0x64, .data = 0x01, .flags = 0b00000011 },
//    90 - TREASURE_CHEST
{ .power = 0x64, .data = 0x01, .flags = 0b00000011 },
//    91 - TREASURE_COFFER
{ .power = 0x05, .data = 0x01, .flags = 0b00010011 },
//    92 - TREASURE_CRATE
{ .power = 0x05, .data = 0x01, .flags = 0b00010011 },
//    93 - TREASURE_TRUNK
{ .power = 0x05, .data = 0x01, .flags = 0b00010011 },
//    94 - TREASURE_URN
{ .power = 0x64, .data = 0x01, .flags = 0b00000011 },
//    95 - TREASURE_VAULT
{ .power = 0x05, .data = 0x01, .flags = 0b00010011 },
//    96 - VEIN_COPPER
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    97 - VEIN_GOLD
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    98 - VEIN_IRON
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    99 - VEIN_SILVER
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    100 - VEIN_TIN
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    101 - WAGON_BROKEN
{ .power = 0x05, .data = 0x01, .flags = 0b00000000 },
//    102 - WARD
{ .power = 0x05, .data = 0x01, .flags = 0b00001100 },
//    103 - WAYSTONE
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    104 - WELL
{ .power = 0x05, .data = 0x01, .flags = 0b00000011 },
//    105 - WELL_ANCIENT
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },
//    106 - WICKER_MAN
{ .power = 0x05, .data = 0x01, .flags = 0b00000010 },

//COUNT = 107;
