// Generated object function headers
// Database contains 43 total objects

// Individual objects strings
ActionOutcome InteractAltar(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractRaft(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractRowBoat(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractBookCase(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractJewelleryCase(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractScrollCase(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractCauldron(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractAcidCloud(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractPoisonGas(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractSmokeCloud(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractCoffin(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractSarcophagus(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractHangingCorpse(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractLaidCorpse(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractBarredDoor(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractIronDoor(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractStoneDoor(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractWickerDoor(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractWoodDoor(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractCave(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractLadder(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractStairs(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractBonfire(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractBrazier(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractCampfire(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractStandingTorch(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractWallTorch(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractAcidFountain(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractBloodFountain(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractWaterFountain(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractHiddenCompartment(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractArmorRack(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractWeaponRack(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractBarrel(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractBasket(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractChest(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractCoffer(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractCrate(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractTrunk(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractUrn(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractVault(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractWard(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);
ActionOutcome InteractWell(HardwareInterface hardware, EntityId object_id, EntityId e_id, ObjectData objectData);

//ALL_NAMES_COUNT = 0;
