// Generated tile function headers
// Database contains 24 total tiles

// Individual tiles strings
bool TIleStepOffCastleFloor(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffDirtFloor(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffMeadowFloor(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffTundraFloor(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffFloorVolcanic(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffWoodFloor(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffFluidAcid(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffFluidCrystal(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffFluidLava(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffFluidWater(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffPitAcid(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffPitLava(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffPitMinor(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffPitSmall(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffPitSnake(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffPitSpike(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffPitWater(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffPitWide(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffRiverFrozen(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffBrickWall(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffCastleWall(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffWallIce(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffStoneWall(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOffWoodWall(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);

//ALL_NAMES_COUNT = 0;
