// Generated tile function headers
// Database contains 24 total tiles

// Individual tiles strings
bool TIleStepOnCastleFloor(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnDirtFloor(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnMeadowFloor(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnTundraFloor(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnFloorVolcanic(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnWoodFloor(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnFluidAcid(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnFluidCrystal(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnFluidLava(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnFluidWater(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnPitAcid(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnPitLava(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnPitMinor(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnPitSmall(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnPitSnake(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnPitSpike(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnPitWater(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnPitWide(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnRiverFrozen(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnBrickWall(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnCastleWall(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnWallIce(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnStoneWall(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);
bool TIleStepOnWoodWall(EntityId id, ObjectsTypes type, uint8_t x, uint8_t y);

//ALL_NAMES_COUNT = 0;
