// Generated tile name strings
// Database contains 24 total entries

// Individual items strings
TIleStepOffCastleFloor,
TIleStepOffDirtFloor,
TIleStepOffMeadowFloor,
TIleStepOffTundraFloor,
TIleStepOffFloorVolcanic,
TIleStepOffWoodFloor,
TIleStepOffFluidAcid,
TIleStepOffFluidCrystal,
TIleStepOffFluidLava,
TIleStepOffFluidWater,
TIleStepOffPitAcid,
TIleStepOffPitLava,
TIleStepOffPitMinor,
TIleStepOffPitSmall,
TIleStepOffPitSnake,
TIleStepOffPitSpike,
TIleStepOffPitWater,
TIleStepOffPitWide,
TIleStepOffRiverFrozen,
TIleStepOffBrickWall,
TIleStepOffCastleWall,
TIleStepOffWallIce,
TIleStepOffStoneWall,
TIleStepOffWoodWall,

//ALL_NAMES_COUNT = 24;
