// Generated tile name strings
// Database contains 24 total entries

// Individual items strings
TIleStepOnCastleFloor,
TIleStepOnDirtFloor,
TIleStepOnMeadowFloor,
TIleStepOnTundraFloor,
TIleStepOnFloorVolcanic,
TIleStepOnWoodFloor,
TIleStepOnFluidAcid,
TIleStepOnFluidCrystal,
TIleStepOnFluidLava,
TIleStepOnFluidWater,
TIleStepOnPitAcid,
TIleStepOnPitLava,
TIleStepOnPitMinor,
TIleStepOnPitSmall,
TIleStepOnPitSnake,
TIleStepOnPitSpike,
TIleStepOnPitWater,
TIleStepOnPitWide,
TIleStepOnRiverFrozen,
TIleStepOnBrickWall,
TIleStepOnCastleWall,
TIleStepOnWallIce,
TIleStepOnStoneWall,
TIleStepOnWoodWall,

//ALL_NAMES_COUNT = 24;
