{
    {.glyph_index = CH_PERIOD,      .fg = PAL_BROWN_GREEN,          .bg = PAL_DARK_GRN_BLACK },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_REDDISH_BROWN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_DARK_GRN_BLACK,       .bg = PAL_GRAYISH_GREEN },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_DARK_RED,             .bg = PAL_PASTEL_GREEN },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_PALE_BLU_PURP },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_PALE_BLU_PURP },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_PALE_BLU_PURP },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_PALE_BLU_PURP },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_PALE_BLU_PURP },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_PALE_BLU_PURP },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_PALE_BLU_PURP },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_PALE_BLU_PURP },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_PALE_BLU_PURP },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY_BLUE,  .bg = PAL_ICE_BLUE},   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_EMERALD_GREEN },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_ORANGISH_RED },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_BROWN_GREEN,          .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_GRAY_BROWN,           .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_DARK_GRN_BLACK,       .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_DARK_RED,             .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY_BLUE,  .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,       .bg = PAL_DEEP_BLUE },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_BROWN_GREEN,        .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_GRAY_BROWN,        .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_DARK_GRN_BLACK,        .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_DARK_RED,          .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY_BLUE,        .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DEEP_BLUE },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_BROWN_GREEN,        .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_GRAY_BROWN,        .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_DARK_GRN_BLACK,        .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_DARK_RED,          .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY_BLUE,        .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DEEP_BLUE },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_BROWN_GREEN,        .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_GRAY_BROWN,        .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_DARK_GRN_BLACK,        .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_DARK_RED,          .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY_BLUE,        .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DEEP_BLUE },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_DARK_BLUE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DEEP_BLUE },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_DARK_BLUE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DEEP_BLUE },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_DARK_BLUE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DEEP_BLUE },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_DARK_BLUE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DEEP_BLUE },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_DARK_BLUE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DEEP_BLUE },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_DARK_BLUE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DEEP_BLUE },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_DARK_BLUE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DEEP_BLUE },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_DARK_BLUE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DEEP_BLUE },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_DARK_BLUE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DEEP_BLUE },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_DARK_BLUE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DEEP_BLUE },   //  lava
},
{
    {.glyph_index = CH_PERIOD,      .fg = PAL_DARK_BLUE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // ground
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_TAN_GREEN },   // wall brick
    {.glyph_index = CH_HASH,        .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_ORANGISH_RED },   // wall stone
    {.glyph_index = CH_AMPERSAND,   .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   // foliage
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_PERIOD,      .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_OFF_WHITE_GRAY },   // water
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DARK_RED },   //  acid
    {.glyph_index = CH_TILDE,       .fg = PAL_OFF_WHITE_GRAY,        .bg = PAL_DEEP_BLUE },   //  lava
}