#pragma once

// Sound IDs for entity type: tile
794,     // 0: FLOOR_CASTLE
795,     // 1: FLOOR_DIRT
796,     // 2: FLOOR_MEADOW
797,     // 3: FLOOR_SNOW
798,     // 4: FLOOR_VOLCANIC
799,     // 5: FLOOR_WOOD
800,     // 6: FLUID_ACID
801,     // 7: FLUID_CRYSTAL
802,     // 8: FLUID_LAVA
803,     // 9: FLUID_WATER
804,     // 10: PIT_ACID
805,     // 11: PIT_LAVA
806,     // 12: PIT_MINOR
807,     // 13: PIT_SMALL
808,     // 14: PIT_SNAKE
809,     // 15: PIT_SPIKES
810,     // 16: PIT_WATER
811,     // 17: PIT_WIDE
812,     // 18: RIVER_FROZEN
813,     // 19: WALL_BRICK
814,     // 20: WALL_CASTLE
815,     // 21: WALL_ICE
816,     // 22: WALL_STONE
817,     // 23: WALL_WOOD
