// Generated creature_buff data structs
// Database contains 16 total used creature_buffs

// Individual creature_buffs data
BERSERK, //0 
FIRE_EATING, //1 
FLYING, //2 
HASTED, //3 
INVIGORATE, //4 
INVISIBLE, //5 
LIFELINK, //6 
MAGIC_SHIELD, //7 
REFLECT, //8 
REGENERATION, //9 
REVITALIZE, //10 
SPELL_POWER, //11 
STONESKIN, //12 
THORNS, //13 
VAMPIRIC_AURA, //14 
WARDED, //15 

//ALL_NAMES_COUNT = 16;
